baseURL = 'https://fengwang.github.io/'
languageCode = 'en-us'
theme = 'hugo-notepadium'
title = "Feng's Blog"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_cache$" ]
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true
favicon = "favicon.ico"

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[params]
description = "Feng's minmal blog."
footer = "&copy; Feng Wang"

[params.math]
enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
#use = "katex"  # option: "katex", "mathjax". default: "katex"
use = "mathjax"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "xcode"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/


[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

